### ISSUE TITLE
Under segmentation for close items

### ISSUE THREAD

**Issue by F2Wang** [bethgelab/siamese-mask-rcnn#29]
First of all, thank you for the great work！

I encounter a problem of under segmenting for instance sitting next to each other, in particular, segmenting a pack of boxes, the algorithm just considers all boxes a single instance.

Is there a way around this if instances are not separated by background? I know the size of the box in pixel space, is there a way I can utilize this information to achieve the correct segmentation? I tried modifying the size and aspect ratio of the anchor boxes but didn't see positive changes.

Thanks in advance!

**Comment by michaelisc** [comment]
In many cases the model should do that automatically but there are two effects working against it:
1. In COCO groups of objects are labelled as "crowds" and detected with a single box
2. The base implementation is from 2017 and the performance is accordingly. A lot has happened since but this cannot easily be transferred to this rather "old" implementation.

**Comment by F2Wang** [comment]
Thank you for the insight!

For the first point, it sounds like the performance will improve If I retrain the coco weight on my custom dataset where instances of a group are labeled separately.

For the second point, is there any "newer" implementation on few-shot instance segmentation that you can point to? Or is there any change you would like to make to this impelemtatation?

**Comment by michaelisc** [comment]
We will likely release a new implementation of this at some point however we have not set any date yet.

**Comment by F2Wang** [comment]
Thank you, looking forward to the update!
